menu:
    Blog: /
    #Archive: /archives/
    Twitter: https://twitter.com/koenkivits
    GitHub: https://github.com/koenkivits
    #RSS: /atom.xml

favicon: /favicon.png
logo: /logo.png

# Copyright Infomation
startyear: 2018
